services:
  order-db:
    image: postgres:17-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OrderDb
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network

  order-api:
    image: shop-platform/order-api:latest
    container_name: order-api
    build:
      context: ../
      dockerfile: src/services/order/Order.Api/Dockerfile
    ports:
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - order-db
      - moderation-api
      - payment-api
      - rabbitmq
    networks:
      - shop-platform-network

  moderation-api:
    image: shop-platform/moderation-api:latest
    container_name: moderation-api
    build:
      context: ../
      dockerfile: src/services/moderation/Moderation.Api/Dockerfile
    ports:
      - "5081:8080"
    networks:
      - shop-platform-network

  payment-db:
    image: postgres:17-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PaymentDb
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-api:
    image: shop-platform/payment-api:latest
    container_name: payment-api
    build:
      context: ../
      dockerfile: src/services/payment/Payment.Api/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      payment-db:
        condition: service_healthy 
    networks:
      - shop-platform-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # UI (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-platform-network

  notification-worker:
     image: shop-platform/notification-worker:latest
     container_name: notification-worker
     build:
       context: ../
       dockerfile: src/services/notification/Notification.Worker/Dockerfile
     environment:
       - RabbitMq__Host=rabbitmq
     depends_on:
       rabbitmq:
         condition: service_healthy
     networks:
       - shop-platform-network
      
volumes:
  order-db-data:
  payment-db-data:

networks:
  shop-platform-network:
    driver: bridge
