services:
  gateway-api:
    image: shop-platform/gateway-api:latest
    container_name: gateway-api
    build:
      context: ../
      dockerfile: src/gateway/Gateway.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - auth-api
      - order-api
    networks:
      - shop-platform-network

  auth-db:
    image: postgres:17-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AuthDb
    ports:
      - "5436:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network

  auth-api:
    image: shop-platform/auth-api:latest
    container_name: auth-api
    build:
      context: ../
      dockerfile: src/services/auth/Auth.Api/Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=auth-db;Port=5432;Database=AuthDb;Username=postgres;Password=postgres;
      - Jwt__Secret=${JWT_SECRET:-development-secret-change-before-production-32-chars}
      - Jwt__Issuer=shop-platform
      - Jwt__Audience=shop-platform
      - Jwt__ExpiresDays=7
    depends_on:
      - auth-db
    networks:
      - shop-platform-network

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OrderDb
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network

  order-api:
    image: shop-platform/order-api:latest
    container_name: order-api
    build:
      context: ../
      dockerfile: src/services/order/Order.Api/Dockerfile
    ports:
      - "5055:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - order-db
    networks:
      - shop-platform-network

volumes:
  auth-db-data:
  order-db-data:

networks:
  shop-platform-network:
    driver: bridge
