services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"
    networks:
      - shop-platform-network

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OrderDb
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network

  order-api:
    image: shop-platform/order-api:latest
    container_name: order-api
    build:
      context: ../
      dockerfile: src/services/order/Order.Api/Dockerfile
    ports:
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__SeqUrl=http://seq:80
    depends_on:
      - order-db
      - moderation-api
      - payment-api
      - rabbitmq
    networks:
      - shop-platform-network

  moderation-api:
    image: shop-platform/moderation-api:latest
    container_name: moderation-api
    build:
      context: ../
      dockerfile: src/services/moderation/Moderation.Api/Dockerfile
    environment:
      - Logging__SeqUrl=http://seq:80
    ports:
      - "5081:8080"
    networks:
      - shop-platform-network
    
  catalog-db:
    image: postgres:17-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network
  
  catalog-api:
    image: shop-platform/catalog-api:latest
    container_name: catalog-api
    build:
      context: ../
      dockerfile: src/services/catalog/Catalog.Api/Dockerfile
    ports:
      - "5056:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog-db
    networks:
      - shop-platform-network
  
  cart-db:
    image: postgres:17-alpine
    container_name: cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CartDb
    ports:
      - "5433:5432"
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network
  
  cart-api:
    image: shop-platform/cart-api:latest
    container_name: cart-api
    build:
      context: ../
      dockerfile: src/services/cart/Cart.Api/Dockerfile
    ports:
      - "5057:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - cart-db
    networks:
      - shop-platform-network
  

  payment-db:
    image: postgres:17-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PaymentDb
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - shop-platform-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-api:
    image: shop-platform/payment-api:latest
    container_name: payment-api
    build:
      context: ../
      dockerfile: src/services/payment/Payment.Api/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - shop-platform-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # UI (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-platform-network

  notification-worker:
     image: shop-platform/notification-worker:latest
     container_name: notification-worker
     build:
       context: ../
       dockerfile: src/services/notification/Notification.Worker/Dockerfile
     environment:
       - RabbitMq__Host=rabbitmq
     depends_on:
       rabbitmq:
         condition: service_healthy
     networks:
       - shop-platform-network
      
volumes:
  order-db-data:
  catalog-db-data:
  cart-db-data:
  payment-db-data:

networks:
  shop-platform-network:
    driver: bridge
